export const dummyOrders = [
  {
    id: "ORD-001",
    name: "Order #ORD-001 - High Value US Order",
    weight: 2.5,
    value: 89.99,
    destination: "US - United States",
    state: "CA",
    postCode: "90210",
    suburb: "Beverly Hills",
    contactName: "John Smith",
    itemCountry: "USA",
    items: [
      { sku: "PROD-123", quantity: 2 },
      { sku: "PROD-456", quantity: 1 },
    ],
    tags: ["priority", "express"],
  },
  {
    id: "ORD-002",
    name: "Order #ORD-002 - Heavy Order",
    weight: 5.2,
    value: 45.0,
    destination: "AU - Australia",
    state: "NSW",
    postCode: "2000",
    suburb: "Sydney",
    contactName: "Jane Doe",
    itemCountry: "Australia",
    items: [{ sku: "HEAVY-001", quantity: 1 }],
    tags: [],
  },
  {
    id: "ORD-003",
    name: "Order #ORD-003 - VIC State Order",
    weight: 1.8,
    value: 32.5,
    destination: "AU - Australia",
    state: "VIC",
    postCode: "3000",
    suburb: "Melbourne",
    contactName: "Bob Wilson",
    itemCountry: "Australia",
    items: [{ sku: "PROD-789", quantity: 3 }],
    tags: ["standard"],
  },
  {
    id: "ORD-004",
    name: "Order #ORD-004 - NZ Avondale Order",
    weight: 1.2,
    value: 28.0,
    destination: "NZ - New Zealand",
    state: "Auckland",
    postCode: "0600",
    suburb: "Avondale",
    contactName: "Sarah Johnson",
    itemCountry: "New Zealand",
    items: [{ sku: "PROD-321", quantity: 1 }],
    tags: [],
  },
  {
    id: "ORD-005",
    name: "Order #ORD-005 - Tagged Order",
    weight: 0.8,
    value: 15.99,
    destination: "AU - Australia",
    state: "QLD",
    postCode: "4000",
    suburb: "Brisbane",
    contactName: "Mike Brown",
    itemCountry: "Australia",
    items: [{ sku: "SMALL-001", quantity: 2 }],
    tags: ["tag", "special"],
  },
  {
    id: "ORD-006",
    name: "Order #ORD-006 - XXX SKU Order",
    weight: 2.1,
    value: 55.0,
    destination: "AU - Australia",
    state: "SA",
    postCode: "5000",
    suburb: "Adelaide",
    contactName: "Emma Davis",
    itemCountry: "Australia",
    items: [{ sku: "XXX-SPECIAL", quantity: 1 }],
    tags: [],
  },
  {
    id: "ORD-007",
    name: "Order #ORD-007 - France Item Order",
    weight: 1.5,
    value: 42.0,
    destination: "AU - Australia",
    state: "WA",
    postCode: "6000",
    suburb: "Perth",
    contactName: "Chris Taylor",
    itemCountry: "France",
    items: [{ sku: "FRENCH-001", quantity: 1 }],
    tags: [],
  },
]
